import { createSlice } from '@reduxjs/toolkit';

export const appSlice = createSlice({
  name: 'app',
  initialState:
  {
    channelId:null,
    channelName:null,
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setChannelInfo: (state,action) => {
     state.channelId=action.payload.channelId;
     state.channelName=action.payload.channelName
    },
   
   },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  
});

export const { setChannelInfo} = appSlice.actions;


export const channelId = (state) => state.app.channelId;
export const channelName = (state) => state.app.channelName;


export default appSlice.reducer;